# Generated by Django 5.0 on 2025-10-31 08:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "citizen",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "status_en",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "status_sw",
                    models.CharField(
                        choices=[
                            ("inayosubiri", "Inayosubiri"),
                            ("imetumwa", "Imetumwa"),
                            ("imeshindwa", "Imeshindwa"),
                        ],
                        default="inayosubiri",
                        max_length=15,
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("report_created", "Report Created"),
                            ("status_updated", "Status Updated"),
                            ("feedback_request", "Feedback Request"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification",
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "constituency",
                    models.CharField(default="Gatundu North", max_length=100),
                ),
                ("county", models.CharField(default="Kiambu", max_length=100)),
                ("population_estimate", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ward",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("leader", "Leader"),
                            ("superadmin", "Super Admin"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_users",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard User",
                "db_table": "dashboard_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("status_change", "Status Change"),
                            ("login", "Login"),
                        ],
                        max_length=20,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.UUIDField()),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_code", models.CharField(max_length=20, unique=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_sw", models.CharField(max_length=200)),
                ("description_en", models.TextField()),
                ("description_sw", models.TextField()),
                (
                    "category_en",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("infrastructure", "Infrastructure"),
                            ("health", "Health"),
                            ("water", "Water"),
                            ("environment", "Environment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category_sw",
                    models.CharField(
                        choices=[
                            ("masomo", "Elimu"),
                            ("miundombinu", "Miundombinu"),
                            ("afya", "Afya"),
                            ("maji", "Maji"),
                            ("mazingira", "Mazungira"),
                            ("mengine", "Mengine"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_en",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("stalled", "Stalled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "status_sw",
                    models.CharField(
                        choices=[
                            ("imepangwa", "Imeplanwa"),
                            ("inaendelea", "Inaendelea"),
                            ("imekamilika", "Imefanyika"),
                            ("imekwama", "Imekwama"),
                        ],
                        default="imepangwa",
                        max_length=20,
                    ),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ref_code", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "category_en",
                    models.CharField(
                        choices=[
                            ("infrastructure", "Infrastructure"),
                            ("education", "Education"),
                            ("health", "Health"),
                            ("security", "Security"),
                            ("environment", "Environment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category_sw",
                    models.CharField(
                        choices=[
                            ("miundombinu", "Miundombinu"),
                            ("elimu", "Elimu"),
                            ("afya", "Afya"),
                            ("usalama", "Usalama"),
                            ("mazingira", "Mazungira"),
                            ("mengine", "Mengine"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status_en",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("under_review", "Under Review"),
                            ("action_taken", "Action Taken"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "status_sw",
                    models.CharField(
                        choices=[
                            ("imepokelewa", "Imepokelewa"),
                            ("chini_ya_kukaguzi", "Chini ya Ukaguzi"),
                            ("tathmini_imefanyika", "Tathmini Imefanyika"),
                            ("imetatuliwa", "Imetatuliwa"),
                            ("imefungwa", "Imefungwa"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "priority_level_en",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "priority_level_sw",
                    models.CharField(
                        choices=[("chini", "Chini"), ("kati", "Kati"), ("juu", "Juu")],
                        default="kati",
                        max_length=10,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.citizen",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="core.project",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "db_table": "report",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.citizen",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.report",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
            },
        ),
        migrations.AddField(
            model_name="citizen",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citizens",
                to="core.ward",
            ),
        ),
    ]
