# Generated by Django 5.0 on 2025-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dashboarduser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="dashboarduser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status_sw",
            field=models.CharField(
                choices=[
                    ("imepangwa", "Imepangwa"),
                    ("inaendelea", "Inaendelea"),
                    ("imekamilika", "Imefanyika"),
                    ("imekwama", "Imekwama"),
                ],
                default="imepangwa",
                max_length=20,
            ),
        ),
    ]
