# Generated by Django 5.0 on 2025-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_update_dashboard_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient_phone",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status_en",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status_sw",
            field=models.CharField(
                choices=[
                    ("inayosubiri", "Inayosubiri"),
                    ("imetumwa", "Imetumwa"),
                    ("imeshindwa", "Imeshindwa"),
                ],
                default="inayosubiri",
                max_length=1200,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("report_created", "Report Created"),
                    ("status_updated", "Status Updated"),
                    ("feedback_request", "Feedback Request"),
                ],
                max_length=300,
            ),
        ),
    ]
